# Generated by Django 2.2.10 on 2020-02-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IlanNo', models.CharField(max_length=50)),
                ('IlanBasligi', models.CharField(max_length=50)),
                ('MansetResmi', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Sepet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KullaniciAdi', models.CharField(max_length=10)),
                ('IlanNo', models.CharField(max_length=20)),
                ('Miktar', models.IntegerField(null=True)),
                ('IsSaved', models.BooleanField(default=False)),
                ('IsVerified', models.BooleanField(default=False)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('IsCanceled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KullaniciAdi', models.CharField(max_length=10)),
                ('SiparisNo', models.CharField(max_length=20)),
                ('IsSaved', models.BooleanField(default=False)),
                ('IsVerified', models.BooleanField(default=False)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('IsCanceled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeslimatOdeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KullaniciAdi', models.CharField(max_length=10)),
                ('Isim', models.CharField(max_length=20)),
                ('Soyisim', models.CharField(max_length=20)),
                ('Tel', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Adres', models.CharField(max_length=200)),
                ('OdemeTipi', models.CharField(max_length=20)),
                ('IsSaved', models.BooleanField(default=False)),
                ('IsVerified', models.BooleanField(default=False)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('IsCanceled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Urunler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kategori', models.CharField(max_length=50)),
                ('AltKategori', models.CharField(max_length=50)),
                ('Marka', models.CharField(max_length=50)),
                ('Model', models.CharField(max_length=50)),
                ('IlanNo', models.CharField(max_length=50)),
                ('IlanBasligi', models.CharField(max_length=50)),
                ('Fiyat', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Miktar', models.IntegerField()),
                ('IlanResmi1', models.ImageField(blank=True, null=True, upload_to='')),
                ('IlanResmi2', models.ImageField(blank=True, null=True, upload_to='')),
                ('IlanResmi3', models.ImageField(blank=True, null=True, upload_to='')),
                ('IlanResmi4', models.ImageField(blank=True, null=True, upload_to='')),
                ('IlanResmi5', models.ImageField(blank=True, null=True, upload_to='')),
                ('IlanResmi6', models.ImageField(blank=True, null=True, upload_to='')),
                ('IlanResmi7', models.ImageField(blank=True, null=True, upload_to='')),
                ('IlanResmi8', models.ImageField(blank=True, null=True, upload_to='')),
                ('IlanResmi9', models.ImageField(blank=True, null=True, upload_to='')),
                ('IlanResmi10', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UrunOzellikleri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IlanNo', models.CharField(max_length=10)),
                ('UrunOzBaslik', models.CharField(max_length=50)),
                ('UrunOzellik', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UrunTanimlamalari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kodu', models.CharField(max_length=10)),
                ('Icerik', models.CharField(max_length=50)),
                ('UstKodu', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vitrin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IlanNo', models.CharField(max_length=50)),
                ('IlanBasligi', models.CharField(max_length=50)),
                ('VitrinResmi', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Yorumlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Yorum', models.CharField(max_length=250)),
                ('Isim', models.CharField(max_length=50)),
                ('Soyisim', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
